'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

fiboEvenSum(10) should return 10.

fiboEvenSum(34) should return 44.

fiboEvenSum(60) should return 44.

fiboEvenSum(1000) should return 798.

fiboEvenSum(100000) should return 60696.

fiboEvenSum(4000000) should return 4613732.
'''

def fiboEvenSum(n):
    if (n <= 1):
        return
    previous = 0
    current = 1
    i = 0
    evenSum = 0
    while (i < n):
        next = current + previous
        previous = current
        current = next
        i += 1
        if ((current % 2 == 0) and (current <= n)):
            evenSum += current

    return evenSum

print(fiboEvenSum(1000))
    